//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mango.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal SellingPrice { get; set; }
        public int RefStoreOrderImportDetailId { get; set; }
        public decimal SupplierPrice { get; set; }
        public decimal MainSupplierPrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual StoreOrderImportDetail StoreOrderImportDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}
