//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mango.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreOrder()
        {
            this.StoreOrderExportDetails = new HashSet<StoreOrderExportDetail>();
            this.StoreOrderImportDetails = new HashSet<StoreOrderImportDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int StoreId { get; set; }
        public StoreOrderStatus Status { get; set; }
        public StoreImExTypeCode StoreImExTypeCode { get; set; }
        public Nullable<System.DateTime> TimeExport { get; set; }
        public Nullable<System.DateTime> TimeImport { get; set; }
        public int UserExportId { get; set; }
        public string Note { get; set; }
        public int UserImportId { get; set; }
        public Nullable<int> RefStoreId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOrderExportDetail> StoreOrderExportDetails { get; set; }
        public virtual Store Store { get; set; }
        public virtual User UserExport { get; set; }
        public virtual User UserImport { get; set; }
        public virtual Store RefStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOrderImportDetail> StoreOrderImportDetails { get; set; }
    }
}
