//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mango.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOrderExportDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreOrderExportDetail()
        {
            this.StoreOrderImportDetails = new HashSet<StoreOrderImportDetail>();
        }
    
        public int Id { get; set; }
        public int StoreOrderId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string Note { get; set; }
        public int RefStoreOrderImportDetailId { get; set; }
        public decimal SupplierPrice { get; set; }
        public decimal MainSupplierPrice { get; set; }
    
        public virtual StoreOrderImportDetail StoreOrderImportDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOrderImportDetail> StoreOrderImportDetails { get; set; }
        public virtual StoreOrder StoreOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
