//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mango.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mango.Resource.EnumText", typeof(EnumText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportFromStoreOther.
        /// </summary>
        public static string StoreImExTypeCode_NhapTuKhoKhac {
            get {
                return ResourceManager.GetString("StoreImExTypeCode.NhapTuKhoKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportFromSupplier.
        /// </summary>
        public static string StoreImExTypeCode_NhapTuNCC {
            get {
                return ResourceManager.GetString("StoreImExTypeCode.NhapTuNCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportToCustomer.
        /// </summary>
        public static string StoreImExTypeCode_XuatBanKhachHang {
            get {
                return ResourceManager.GetString("StoreImExTypeCode.XuatBanKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportStoreOther.
        /// </summary>
        public static string StoreImExTypeCode_XuatKhoKhac {
            get {
                return ResourceManager.GetString("StoreImExTypeCode.XuatKhoKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt .
        /// </summary>
        public static string UserStatus_Active {
            get {
                return ResourceManager.GetString("UserStatus.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        public static string UserStatus_InActive {
            get {
                return ResourceManager.GetString("UserStatus.InActive", resourceCulture);
            }
        }
    }
}
